# 数据源配置
spring:
  application:
    name: AutoPartTime
  datasource:
    url: jdbc:mysql://localhost:3306/admin-backend?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false
    username: root  # 数据库用户名
    password: root  # 数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver  # 数据库驱动类名
