server:
  port: 8900
  servlet:
    context-path: /admin-backend

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

#sms短信配置
sms:
  app-code: 86deba2ccedd415882ac15010e98ce8d
  template-id: JM1000372
  app-key: 204575450
  app-secret: bkvG5bx8QztuiKwRZMxL2XHNFseAtzVM